name: Dev deploy

on:
  push:
    branches:
      - dev

permissions:


jobs:
  terraform:
    secrets:
      AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
    uses: ./.github/workflows/terraform.yaml
    with:
      environment: dev
      aws_region: us-east-1
    #  aws_lock_dynamodb_table: terraform-statelock-us-east-1
    #  aws_statefile_s3_bucket: terraform-statefile-us-east-1
