name: Prod deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yaml
    with:
      environment: prod
      aws_assume_role_arn: "${{ secrets.AWS_ASSUME_ROLE_ARN }}"
      aws_region: "us-east-1"
      aws_statefile_s3_bucket: "${{ vars.AWS_STATEFILE_S3_BUCKET }}"
      aws_lock_dynamodb_table: "${{ vars.AWS_LOCK_DYNAMODB_TABLE }}"
  
