name: Terraform workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      aws_assume_role_arn:
        required: true
        type: string
      aws_region:
        required: true    
        type: string  
        default: "us-east-1"
      aws_statefile_s3_bucket:
        required: true
        type: string
      aws_lock_dynamodb_table:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws_assume_role_arn }}
          role-session-name: Terraform_OIDC
          region: ${{ inputs.aws_region }}
      
      - name: Terraform Init
        run: |
          cd infra && terraform init \
            -backend-config="bucket=${{ inputs.aws_statefile_s3_bucket }}" \
            -backend-config="key=${{ github.event.repository.name }}.tfstate" \
            -backend-config="region=${{ inputs.aws_region }}" \
            -backend-config="dynamodb_table=${{ inputs.aws_lock_dynamodb_table }}"

      - name: Terraform Validate
        run: |
          cd infra && terraform validate

      - name: Terraform Plan
        run: |
          cd infra && 
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform plan -var-file="./envs/${{ inputs.environment }}.tfvars" -out="${{ inputs.environment }}.tfplan"

      - name: Terraform Apply
        run: |
          cd infra &&
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform apply "${{ inputs.environment }}.tfplan"